{
 "title": "Downloader",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "VPN Tunnel (tun0) Receive Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"downloader.*\",interface=\"tun0\"}[5m])",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Current Download Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"downloader.*\",interface=\"tun0\"}[5m])"
    }
   ]
  },
  {
   "title": "Downloader CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"default\",container=\"downloader\"}  [5m]))"
    }
   ]
  },
  {
   "title": "Downloader Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\",container=\"downloader\"}"
    }
   ]
  },
  {
   "title": "Transmit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"downloader.*\"}[5m])",
     "legendFormat": "{{interface}} ({{pod}} on {{instance}})"
    }
   ]
  }
 ]
}