{
 "title": "Kubernetes Nodes",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Noad Load (1 min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "Node Load (5 min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "Node Load (15 min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100 - (avg by (kubernetes_node) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)  ",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  }
 ]
}